ws-run-audio updates

diff --git a/ws-run-audio b/ws-run-audio
--- a/ws-run-audio
+++ b/ws-run-audio
@@ -21,10 +21,17 @@ if [[ "$(pgrep -c ws-run-audio)" -gt 1 ]]; then
   exit 1
 fi
 
+trap "echo 'Terminating ws-run-audio...'; exit 0" SIGINT SIGTERM
+
 echo "Starting ws-run-audio..."
 
 #Config
-CONFIG=$(cat /etc/ws/audio.conf)
+CONFIG_FILE="/etc/ws/audio.conf"
+if [[ ! -f "$CONFIG_FILE" || ! -r "$CONFIG_FILE" ]]; then
+  echo "Error: Config file '$CONFIG_FILE' not found or not readable."
+  exit 2
+fi
+CONFIG=$(cat "$CONFIG_FILE")
 
 #Check config exists
 if [[ -z "$CONFIG" ]]; then
@@ -36,8 +43,8 @@ COUNTDOWN=5
 FNTYPE=$(echo "$CONFIG" | jq -r '.init .filenaming')
 
 function onOff {
-  pi-pwr off $(echo "$CONFIG" | jq -r '.init .off[]' | tr '\n' ' ')
-  pi-pwr on $(echo "$CONFIG" | jq -r '.init .on[]' | tr '\n' ' ')
+  pi-pwr off "$(echo "$CONFIG" | jq -r '.init .off[]' | tr '\n' ' ')"
+  pi-pwr on "$(echo "$CONFIG" | jq -r '.init .on[]' | tr '\n' ' ')"
 }
 
 while true;
@@ -53,6 +60,8 @@ do
 					;;
 	esac
 
+	LATEST_RECORD=""
+
 	N=$(echo "$CONFIG" | jq -r ".run | length")
 	I=0
 	while [ $I  -lt $N ];
@@ -63,55 +72,58 @@ do
 		echo $ACTION
 		sudo ws-heartbeat $ACTION &
         	case  $ACTION in
-			record)
-				DURATION=`echo $CONFIG| jq -r ".run[$I] .duration"`
-				CHANNELS=`echo $CONFIG| jq -r ".run[$I] .channels"`
-				BITRATE=`echo $CONFIG| jq -r ".run[$I] .bitrate"`
-				FORMAT=`echo $CONFIG| jq -r ".run[$I] .format"`
-				ws-indicate record "arecord -c $CHANNELS -r $BITRATE -f $FORMAT -d $DURATION $FN.wav"
-				;;
-			sleep)
-				sleep `echo $CONFIG| jq -r ".run[$I] .duration"`
-				;;
-			upload)
-				;;
-			upload-delete)
-				METHOD=`echo $CONFIG| jq -r ".run[$I] .method"`
-				UPPATH=`echo $CONFIG| jq -r ".run[$I] .path"`
-				EXTENSION=`echo $CONFIG| jq -r ".run[$I] .extension"`
-				ASYNC=`echo $CONFIG| jq -r ".run[$I] .async"`
-				case $METHOD in
-					s3cmd)
-						S3UP=`eval echo "s3cmd put $FN.$EXTENSION s3://$UPPATH"`
-						S3UP="$S3UP && rm $FN.$EXTENSION"
-						if [[ "$ASYNC" == "true" ]]; then
-						  S3UP="( $S3UP )&";
-						fi
-						eval $S3UP
-						;;
-					mv)
-						MVUPPATH=$(eval "echo ${UPPATH}")
-						
-						# Check if the destination directory exists
-						if [[ ! -d "$MVUPPATH" ]]; then
-								mkdir -p "$MVUPPATH"
-						fi
+				record)
+					DURATION=`echo $CONFIG| jq -r ".run[$I] .duration"`
+					CHANNELS=`echo $CONFIG| jq -r ".run[$I] .channels"`
+					BITRATE=`echo $CONFIG| jq -r ".run[$I] .bitrate"`
+					FORMAT=`echo $CONFIG| jq -r ".run[$I] .format"`
+					ws-indicate record "arecord -c $CHANNELS -r $BITRATE -f $FORMAT -d $DURATION $FN.wav"
+					LATEST_RECORD=$FN
+					;;
+				sleep)
+					sleep `echo $CONFIG| jq -r ".run[$I] .duration"`
+					;;
+				upload-delete)
+					if [[ "$LATEST_RECORD" == "" ]]; then
+						echo "Trying to upload before recording made." 1>&2
+						echo "Skipping upload." 1>&2
+						break
+					fi
+					;;
+				mv)
+					if [[ "$LATEST_RECORD" == "" ]]; then
+						echo "Trying to mv before recording made." 1>&2
+						echo "Skipping mv." 1>&2
+						break
+					fi
 
-						mv $FN.$EXTENSION $MVUPPATH &
-						;;
-					script)
-						SCRIPT=`echo $CONFIG| jq -r ".run[$I] .script"`
-						# Check if the script exists and is executable
-						if [[ -x "$SCRIPT" ]]; then
-							$SCRIPT $FN $EXTENSION &
-						else
-							echo "Script $SCRIPT not found or not executable."
-						fi
-						;;
-				esac
-				;;
-			clearup)
-				;;
+					MVUPPATH=$(eval "echo ${UPPATH}")
+					
+					# Check if the destination directory exists
+					if [[ ! -d "$MVUPPATH" ]]; then
+							mkdir -p "$MVUPPATH"
+					fi
+
+					mv $FN.$EXTENSION $MVUPPATH &
+					;;
+				script)
+				if [[ "$LATEST_RECORD" == "" ]]; then
+						echo "Trying to pass file to script before recording made." 1>&2
+						echo "Skipping." 1>&2
+						break
+					fi
+					SCRIPT=`echo $CONFIG| jq -r ".run[$I] .script"`
+					# Check if the script exists and is executable
+					if [[ -x "$SCRIPT" ]]; then
+						$SCRIPT $FN $EXTENSION &
+					else
+						echo "Script $SCRIPT not found or not executable."
+					fi
+					;;
+			esac
+					;;
+				clearup)
+					;;
 		esac
 
 		I=$(($I + 1))
